# Generated by Django 4.2.2 on 2023-06-12 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0002_project_author_project_is_finish_project_people_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='information',
            field=models.TextField(null=True),
        ),
    ]
