# Generated by Django 4.2.2 on 2023-06-12 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0003_project_information'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='people',
        ),
        migrations.AlterField(
            model_name='project',
            name='content',
            field=models.TextField(verbose_name='모집 프로그램 상세 설명'),
        ),
        migrations.AlterField(
            model_name='project',
            name='information',
            field=models.TextField(null=True, verbose_name='연락처(선발된 사용자에게만 보임)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='question1',
            field=models.CharField(max_length=100, null=True, verbose_name='지원서 첫번째 질문'),
        ),
        migrations.AlterField(
            model_name='project',
            name='question2',
            field=models.CharField(max_length=100, null=True, verbose_name='지원서 두번째 질문'),
        ),
        migrations.AlterField(
            model_name='project',
            name='question3',
            field=models.CharField(max_length=100, null=True, verbose_name='지원서 세번째 질문'),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=50, verbose_name='모집 프로그램명'),
        ),
    ]
