# Generated by Django 4.2.2 on 2023-06-12 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0004_remove_project_people_alter_project_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='information',
            field=models.TextField(blank=True, null=True, verbose_name='연락처(선발된 사용자에게만 보임)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='question1',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='지원서 첫번째 질문'),
        ),
        migrations.AlterField(
            model_name='project',
            name='question2',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='지원서 두번째 질문'),
        ),
        migrations.AlterField(
            model_name='project',
            name='question3',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='지원서 세번째 질문'),
        ),
    ]
