# Generated by Django 4.2.2 on 2023-06-14 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0005_alter_project_information_alter_project_question1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='information',
            field=models.TextField(blank=True, null=True, verbose_name='합격 메시지(선발된 사용자에게만 보임)'),
        ),
    ]
