# Generated by Django 4.2.2 on 2023-06-14 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0006_alter_project_information'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='question1',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='지원서 첫 번째 질문'),
        ),
        migrations.AlterField(
            model_name='project',
            name='question2',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='지원서 두 번째 질문'),
        ),
        migrations.AlterField(
            model_name='project',
            name='question3',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='지원서 세 번째 질문'),
        ),
    ]
